import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumb } from "@/components/Breadcrumb";
import { GameCard } from "@/components/GameCard";
import { SEOHead } from "@/components/SEOHead";
import { categories, getCategory, getCategoryPage, getCategoryPageCount, getGamesByCategory, MIN_INDEXABLE_CATEGORY_GAMES } from "@/lib/games";
import { pageMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/site";

const categoryCopy: Record<string, { title: string; description: string; intro: string }> = {
  "local-2-player": { title: "Local 2 Player Games – Same Keyboard & Same Computer | Games for Many", description: "Play 2 player games on one computer with a shared keyboard or pass-and-play controls. Fighting, board, racing – no download, no signup.", intro: "Two people, one computer, one keyboard – no matchmaking, no signup, no waiting for a server. These are the games you load when a friend is sitting next to you and you both want to play right now. Split the keyboard (WASD vs arrows), pass the mouse for board games, or hand off the controller between rounds." },
  "online-2-player": { title: "Online 2 Player Games – Play with a Friend Remotely | Games for Many", description: "2 player browser games you can play with a friend on separate devices. Room codes, matchmaking or public opponents – no download.", intro: "Play a friend on the other side of the country, or match a random opponent in seconds. These are two-player games where each person opens the page on their own device – phone, laptop, tablet – and the game handles the connection. Some use share codes so you can pick who you play; others drop you straight into public matchmaking for a quick duel." },
  "multiplayer": { title: "Multiplayer Browser Games – Play with Real People Online | Games for Many", description: "Free multiplayer browser games with real players. Team battles, public arenas, room codes and 2-4 player games – no download, no signup.", intro: "Games where you're playing against or with real people, not AI. The catalog covers everything from head-to-head duels to public arenas with dozens of players. Some let you match a specific friend through a room code; others drop you into whatever match has an open slot. All of them run in a browser tab – no launcher, no install." },
  "party": { title: "Party Games Online – Fun Games for Groups | Games for Many", description: "Quick browser party games for 2-4 people. Races, knockouts, shared-keyboard chaos and party card games – rotate players in under a minute.", intro: "The games you load when a group of people is standing around one laptop, or when you want a rematch every 90 seconds. Party games here are short, easy to explain, and just as fun to watch as to play. Some run on a shared keyboard, some go online, and a couple support a third player using the mouse." },
  "board-card": { title: "2 Player Board & Card Games Online – Free Browser Play | Games for Many", description: "Classic board and card games for 2 players. Checkers, chess, backgammon, dominoes, WHOT and more – solo, online or pass-and-play.", intro: "The turn-based side of the catalog. Classic board games (checkers, chess, backgammon, reversi), traditional card games (WHOT, dominoes, Uno-style) and modern tabletop-inspired titles. Play against a live opponent online, pass one device back and forth, or practice against the computer while you're learning the rules." },
  "sports-racing": { title: "2 Player Sports & Racing Browser Games | Games for Many", description: "Free sports and racing games for 2 players. Pong, darts, billiards, carrom, arcade soccer and obstacle races – online or same-computer.", intro: "Competitive games built around aiming, timing or racing to a finish. Pong-style paddle games, darts and billiards for precision, arcade soccer for chaos, and obstacle races when you want a clear winner in under 90 seconds. Some play locally on one keyboard, some connect you with an opponent online." },
  "io-arena": { title: "IO & Arena Games – Free Browser Battle Royale & Multiplayer | Games for Many", description: "Play free .io games and online arena games. Battle royale, snake survival, territory wars, social deduction – no download, jump in fast.", intro: "Lightweight browser games built around real-time public matches. Battle royale, territory painting, snake survival, social deduction, trivia races – IO games are the fastest way to jump into a live match against real people. No signup, no download, most matches under five minutes." },
};

export function generateStaticParams() { return categories.map((category) => ({ slug: category.slug })); }

export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const category = getCategory(params.slug);
  if (!category) return {};
  const copy = categoryCopy[category.slug];
  const metadata = pageMetadata(copy?.title ?? `Free ${category.title} Games Online`, copy?.description ?? category.description, `/category/${category.slug}/`);
  if (copy) {
    metadata.title = { absolute: copy.title };
    const socialTitle = copy.title.replace(/\s*\|\s*Games for Many$/, "").replace(/\bFree\b\s*/g, "").replace(/\s{2,}/g, " ").trim();
    metadata.openGraph = { ...metadata.openGraph, title: socialTitle };
    metadata.twitter = { ...metadata.twitter, title: socialTitle };
  }
  if (getGamesByCategory(category.slug).length < MIN_INDEXABLE_CATEGORY_GAMES) metadata.robots = { index: false, follow: true };
  return metadata;
}

export default function CategoryPage({ params }: { params: { slug: string } }) {
  const category = getCategory(params.slug);
  if (!category) notFound();
  const games = getCategoryPage(category.slug, 1);
  const pageCount = getCategoryPageCount(category.slug);
  const isLocal = category.slug === "local-2-player";
  const isOnlineTwoPlayer = category.slug === "online-2-player";
  const isMultiplayer = category.slug === "multiplayer";
  const isParty = category.slug === "party";
  const isBoardCard = category.slug === "board-card";
  const isSportsRacing = category.slug === "sports-racing";
  const isIoArena = category.slug === "io-arena";
  const schema = (isLocal || isOnlineTwoPlayer || isMultiplayer || isParty || isBoardCard || isSportsRacing || isIoArena) ? { "@context": "https://schema.org", "@type": "CollectionPage", name: `${category.title} Games`, url: `${siteConfig.url}/category/${category.slug}/`, description: category.description, mainEntity: { "@type": "ItemList", numberOfItems: getGamesByCategory(category.slug).length, itemListElement: games.map((game, index) => ({ "@type": "ListItem", position: index + 1, url: `${siteConfig.url}/games/${game.slug}/`, name: game.title })) } } : null;
  return (
    <div className="page-shell">
      {schema && <SEOHead data={schema} />}
      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: `${category.title} Games` }]} />
      <h1 className="text-4xl font-black text-slate-950">{category.title} Games</h1>
      <p className="mt-4 max-w-3xl leading-7 text-slate-600">{categoryCopy[category.slug]?.intro ?? category.description}</p>
      {games.length ? <div className="game-grid mt-8">{games.map((game) => <GameCard game={game} key={game.slug} />)}</div> : <p className="mt-8 rounded-2xl bg-white p-6 text-slate-600">The first reviewed games for this category are being selected.</p>}
      {pageCount > 1 && <nav aria-label="Category pages" className="mt-10 flex flex-wrap gap-2">{Array.from({ length: pageCount }, (_, index) => index + 1).map((page) => <Link aria-current={page === 1 ? "page" : undefined} className={`rounded-lg border px-4 py-2 ${page === 1 ? "border-violet-700 bg-violet-700 text-white" : "border-slate-300 bg-white text-slate-700"}`} href={page === 1 ? `/category/${category.slug}/` : `/category/${category.slug}/page/${page}/`} key={page}>{page}</Link>)}</nav>}
      {isLocal && <section className="prose-copy mt-14">
        <h2>{"Best 2 player games at home – same keyboard, same screen"}</h2>
        <p>{"Local two-player games are the fastest way to play with someone who's physically in the room with you. No account, no invite links, no ping issues – just load the page and pick who's WASD and who's arrows. This collection covers three setups: shared keyboard (both players moving at the same time), pass-and-play (turn-based, one mouse), and mixed (two on keyboard, one on mouse for a third player)."}</p>
        <h2>{"Fun 2 player games with split-keyboard controls"}</h2>
        <p>{"Simultaneous keyboard play is the classic couch setup. "}<Link href="/games/nightmare-runners/">{"Nightmare Runners"}</Link>{" splits movement and jumping between two players and puts them in the same obstacle course. "}<Link href="/games/gang-fall-party/">{"Gang Fall Party"}</Link>{" gives each player independent movement, run and punch, so it plays more like a fighting game. "}<Link href="/games/duo-water-and-fire/">{"Duo Water and Fire"}</Link>{" is the classic fire-and-water two-player formula – water avoids lava, fire avoids water, both need the key. "}<Link href="/games/mcatlants/">{"MCATLANTS"}</Link>{" works best when both players coordinate on objectives instead of competing."}</p>
        <h2>{"Pass-and-play board games for 2 people"}</h2>
        <p>{"When you don't want to fit four hands on one keyboard, use turn-based games that share a single mouse or touchscreen. "}<Link href="/games/carrom-pro/">{"Carrom Pro"}</Link>{" has three rulesets (Classic, Disc Pool, Freestyle) and clean physics that feel closer to a real wooden board than most browser versions. "}<Link href="/games/master-checkers-multiplayer/">{"Master Checkers Multiplayer"}</Link>{" and "}<Link href="/games/turkish-draughts/">{"Turkish Draughts"}</Link>{" run standard tabletop rules with forced captures. "}<Link href="/games/backgammonia-online-backgammon-game/">{"Backgammonia"}</Link>{" has a dice-based flow that's naturally suited to sharing one pointer."}</p>
        <h2>{"Games for 3 players on one device"}</h2>
        <p>{"Most games here are built for two, but a few document a third-player slot. "}<Link href="/games/fish-eat-getting-big/">{"Fish Eat Getting Big"}</Link>{" and "}<Link href="/games/fish-eat-fish-2/">{"Fish Eat Fish 2"}</Link>{" let two people use keyboard layouts and a third person use the mouse. Handy when someone joins mid-session."}</p>
        <h2>{"Local vs online 2 player – which to pick"}</h2>
        <p>{"Load a local game when you and your friend are in the same room and share one screen. If you're playing with someone remote, browse "}<Link href="/category/online-2-player/">{"online two-player games"}</Link>{" instead – matchmaking or room codes will connect you across devices. Games tagged \"both\" work either way. For larger groups, the full "}<Link href="/category/multiplayer/">{"multiplayer collection"}</Link>{" has team formats and public arenas."}</p>
        <h2>{"Frequently asked questions"}</h2>
        <div><h3>{"Can two people really play these on one computer?"}</h3><p>{"Yes. Every game here supports either a shared keyboard (both players active at once), pass-and-play turns on one mouse, or a mix of both. The player count and control setup is listed on each game page."}</p></div>
        <div><h3>{"Do I need a second controller or gamepad?"}</h3><p>{"No. All the games in this collection are designed around keyboard sharing or mouse passing. Some also accept a gamepad if you have one, but nothing here requires it."}</p></div>
        <div><h3>{"Which games work best for couples?"}</h3><p>{"For couples specifically, "}<Link href="/games/duo-water-and-fire/">{"Duo Water and Fire"}</Link>{" (cooperative puzzles), "}<Link href="/games/nightmare-runners/">{"Nightmare Runners"}</Link>{" (side-by-side races) and "}<Link href="/games/master-checkers-multiplayer/">{"Master Checkers Multiplayer"}</Link>{" (slower strategy) are the three most-played picks."}</p></div>
        <div><h3>{"Can I play these games offline?"}</h3><p>{"The games are HTML5 embeds that load through the browser, so you need an internet connection the first time. Some may cache and keep working briefly if the tab stays open, but they're not designed as offline games."}</p></div>
        <p>For more ways to choose a shared-device game, read our <Link href="/blog/best-2-player-browser-games/">two-player browser game testing guide</Link>.</p>
      </section>}
      {isOnlineTwoPlayer && <section className="prose-copy mt-14">
        <h2>{"How online 2 player browser games work"}</h2>
        <p>{"Every game here connects two people on separate devices. Some use a share code – one player creates a room, the other pastes the code – so you always know who you're playing. Others use public matchmaking, where the game pairs you with the next available opponent in seconds. A few include both. Most also have an AI practice mode, but \"AI-only\" games don't count as multiplayer, so nothing in this list qualifies through AI alone."}</p>
        <h2>{"Play with a friend using a room code"}</h2>
        <p>{"If you want to pick who you play, look for room codes and private invites. "}<Link href="/games/ninja-parkour-multiplayer/">{"Ninja Parkour Multiplayer"}</Link>{" lets you either drop into a public room or create a private one and share the code – ideal for a quick session with a specific friend. "}<Link href="/games/multiplayer-pong/">{"Multiplayer Pong"}</Link>{" has the same private/public split for a shorter format."}</p>
        <h2>{"Quick online matches with a random opponent"}</h2>
        <p>{"Public matchmaking is faster when nobody specific is around. "}<Link href="/games/tic-tac-toe-pro-multiplayer-challenge/">{"Tic Tac Toe Pro"}</Link>{" finds an opponent in seconds and matches last under a minute – it's a rematch machine. "}<Link href="/games/greedy-snake-multiplayer-duel/">{"Greedy Snake Multiplayer Duel"}</Link>{" drops you into a short arena, and "}<Link href="/games/music-night-battle-rhythm-game/">{"Music Night Battle"}</Link>{" uses timing instead of aim for the competitive element."}</p>
        <h2>{"Online board games and card duels"}</h2>
        <p>{"Slower games where connection speed doesn't decide the match. "}<Link href="/games/dominoes-classic-duel/">{"Dominoes Classic Duel"}</Link>{", "}<Link href="/games/master-checkers-multiplayer/">{"Master Checkers Multiplayer"}</Link>{", "}<Link href="/games/turkish-draughts/">{"Turkish Draughts"}</Link>{" and "}<Link href="/games/whot-the-ultimate-nigerian-card-game/">{"WHOT"}</Link>{" are all turn-based, so lag isn't a factor. Good picks if one of you is on a weaker connection."}</p>
        <h2>{"Real-time competitive games"}</h2>
        <p>{"For head-to-head action, "}<Link href="/games/battle-jitsu/">{"Battle Jitsu"}</Link>{" and "}<Link href="/games/black-and-white-stickman/">{"Black and White Stickman"}</Link>{" run short competitive rounds where reaction time actually matters. "}<Link href="/games/rocketcar-cup/">{"Rocketcar Cup"}</Link>{" turns arcade soccer into a real-time 2-player match."}</p>
        <h2>{"Online vs local 2 player games"}</h2>
        <p>{"Use online play when you and your friend aren't in the same room. If you're sharing one screen, switch to "}<Link href="/category/local-2-player/">{"local two-player games"}</Link>{" – the setup is instant. Games marked \"both\" let you choose either mode depending on who's available. For larger sessions with three or more players, "}<Link href="/category/multiplayer/">{"multiplayer games"}</Link>{" covers rooms, teams and public arenas."}</p>
        <h2>{"Frequently asked questions"}</h2>
        <div><h3>{"Can I play with a specific friend, or only random opponents?"}</h3><p>{"Depends on the game. Ninja Parkour Multiplayer, Multiplayer Pong and Chess Multiplayer Online support share codes and private rooms. Others (Tic Tac Toe Pro, Greedy Snake Duel) are public matchmaking only. Each game page lists which is supported."}</p></div>
        <div><h3>{"Do both players need to sign up?"}</h3><p>{"No. Every online game here loads in the browser without an account. Some let you set a display name, but you don't create a profile."}</p></div>
        <div><h3>{"What happens if my opponent disconnects mid-game?"}</h3><p>{"Most games either give you the win, wait a few seconds for reconnection, or drop you back to matchmaking so you can start a new match. Behavior varies – nothing here charges you for a disconnect."}</p></div>
        <div><h3>{"Do these work on phones?"}</h3><p>{"Most do. The game page shows whether the game is mobile-optimized. Board games (checkers, dominoes, WHOT) play especially well on phone since they're touch-based."}</p></div>
        <p>For larger online rounds, try <Link href="/games/gang-fall-party/">Gang Fall Party</Link> or <Link href="/games/nightmare-runners/">Nightmare Runners</Link>. Our <Link href="/blog/best-2-player-browser-games/">two-player browser game testing guide</Link> covers controls and modes.</p>
      </section>}
      {isMultiplayer && <section className="prose-copy mt-14">
        <h2>{"What counts as a multiplayer game here"}</h2>
        <p>{"A game qualifies for this collection if it has a real online player mode – not \"multiplayer\" as a supplier tag with no actual online play behind it. AI practice can be included as an extra mode, but AI-only games don't make the list. If you want a duel specifically with one other person, jump to "}<Link href="/category/online-2-player/">{"online 2-player games"}</Link>{". If two people are sharing one device, use "}<Link href="/category/local-2-player/">{"local 2-player games"}</Link>{" instead."}</p>
        <h2>{"Quick 1v1 multiplayer matches"}</h2>
        <p>{"For a direct contest with no waiting for a lobby to fill, "}<Link href="/games/multiplayer-pong/">{"Multiplayer Pong"}</Link>{", "}<Link href="/games/battle-jitsu/">{"Battle Jitsu"}</Link>{" and "}<Link href="/games/music-night-battle-rhythm-game/">{"Music Night Battle"}</Link>{" all focus on one clear mechanic and finish in a couple of minutes. Good picks if you want to run a best-of-five while you're on a call with a friend."}</p>
        <h2>{"Public arenas and larger battles"}</h2>
        <p>{"For unpredictable public matches, "}<Link href="/games/iron-legion/">{"Iron Legion"}</Link>{" runs team tank battles with ten-plus vehicle classes and control-point maps. "}<Link href="/games/tung-sahur-io/">{"Tung Sahur IO"}</Link>{", "}<Link href="/games/guardz-io/">{"Guardz IO"}</Link>{" and "}<Link href="/games/snake-war-multiplayer/">{"Snake War Multiplayer"}</Link>{" focus on public opponents in an open arena. "}<Link href="/games/survev-io/">{"Survev.io"}</Link>{" is a top-down battle royale where you loot buildings and stay inside a shrinking safe zone."}</p>
        <h2>{"Co-op, teams and social deduction"}</h2>
        <p>{"Not every multiplayer game is competitive. "}<Link href="/games/pga3-zombie/">{"PGA3 Zombie"}</Link>{" documents online co-op play against waves of enemies. "}<Link href="/games/imposter-duck-online/">{"Imposter Duck: Online"}</Link>{" is a social deduction game with hidden roles – closer to a party format than a shooter."}</p>
        <h2>{"2-player games in the multiplayer catalog"}</h2>
        <p>{"Head-to-head titles like "}<Link href="/games/master-checkers-multiplayer/">{"Master Checkers Multiplayer"}</Link>{", "}<Link href="/games/nightmare-runners/">{"Nightmare Runners"}</Link>{", "}<Link href="/games/ninja-parkour-multiplayer/">{"Ninja Parkour Multiplayer"}</Link>{" and "}<Link href="/games/gang-fall-party/">{"Gang Fall Party"}</Link>{" also appear in this collection because they support online play against real opponents. They're easier to organize with a specific friend than arena games."}</p>
        <h2>{"How this catalog is organized"}</h2>
        <p>{"The pool of \"multiplayer\" as a supplier category is bigger than what's listed here – games get filtered out if they only show AI on review, if the multiplayer mode is broken or has no active players, or if the audience isn't suitable for a general-audience site. That's why the count is smaller than what you'd see on a raw supplier feed."}</p>
        <h2>{"Frequently asked questions"}</h2>
        <div><h3>{"How is multiplayer different from 2 player?"}</h3><p>{"Multiplayer is the broad category and includes head-to-head duels, larger rooms, team games and public arenas. Two-player specifically means a match designed around two people. If you want a duel, "}<Link href="/category/online-2-player/">{"online 2-player games"}</Link>{" is the narrower filter."}</p></div>
        <div><h3>{"Can I play multiplayer games with a specific friend?"}</h3><p>{"Some games (Ninja Parkour Multiplayer, Multiplayer Pong, Chess Multiplayer Online) support room codes for private invites. Public arenas like Iron Legion or Survev.io use public matchmaking. Check the game page for the connection method."}</p></div>
        <div><h3>{"Do these games need a download?"}</h3><p>{"No. Everything on the site is browser-based. A game may still have its own loading screen or optional account features, but nothing installs to your device."}</p></div>
        <div><h3>{"Are these games free?"}</h3><p>{"Yes. All games load for free. Individual games may show ads or offer optional cosmetics, but there's no site subscription or paywall."}</p></div>
        <p>Our <Link href="/blog/best-2-player-browser-games/">two-player browser game testing guide</Link> has more detail on controls and player modes.</p>
      </section>}
      {isParty && <section className="prose-copy mt-14">
        <h2>{"What makes a good browser party game"}</h2>
        <p>{"Party games need three things: a rule you can explain in ten seconds, rounds that finish in a couple of minutes, and enough visible chaos that spectators keep watching. Long tutorials kill the vibe. Everything in this collection is picked for how quickly you can hand off the keyboard to the next player."}</p>
        <h2>{"Fun party games for 2 players"}</h2>
        <p><Link href="/games/table-pong/">{"Table Pong"}</Link>{" and "}<Link href="/games/drunken-duel-2-players/">{"Drunken Duel 2 Players"}</Link>{" are the fastest picks – you're playing within five seconds of loading. "}<Link href="/games/music-night-battle-rhythm-game/">{"Music Night Battle"}</Link>{" works well when players prefer timing and rhythm over reaction speed. Rounds are short enough that you can run a full mini-tournament in fifteen minutes."}</p>
        <h2>{"Shared-screen games for 3 players"}</h2>
        <p>{"A few games explicitly document a third player controlled by the mouse. "}<Link href="/games/fish-eat-getting-big/">{"Fish Eat Getting Big"}</Link>{" and "}<Link href="/games/fish-eat-fish-2/">{"Fish Eat Fish 2"}</Link>{" both work this way – two people on split-keyboard layouts and a third person on the mouse. Practical when an extra person wants to join without setting up a whole new device."}</p>
        <h2>{"Races, knockouts and chaos formats"}</h2>
        <p>{"The most spectator-friendly formats are races and elimination rounds. "}<Link href="/games/nightmare-runners/">{"Nightmare Runners"}</Link>{" and "}<Link href="/games/gang-fall-party/">{"Gang Fall Party"}</Link>{" run knockout-style obstacle courses. "}<Link href="/games/aquapark-balls-party/">{"Aquapark Balls Party"}</Link>{" and "}<Link href="/games/brainrot-bridge-race-3d/">{"Brainrot Bridge Race 3D"}</Link>{" are pure racing – whoever crosses the finish first wins, no interpretation needed. Ideal when the audience wants to follow the outcome without learning rules."}</p>
        <h2>{"Card and board games for a party session"}</h2>
        <p><Link href="/games/dominoes-classic-duel/">{"Dominoes Classic Duel"}</Link>{" is short enough for a party rotation and doesn't require deep strategy knowledge. "}<Link href="/games/multiplayer-cooking-coop/">{"Multiplayer Cooking Coop"}</Link>{" works for cooperative party sessions where the goal is beating the clock rather than beating each other."}</p>
        <h2>{"Local vs online party games"}</h2>
        <p>{"If everyone is in the same room, load a local game and share the device – nothing to explain, nothing to install. If people are joining from separate locations, use "}<Link href="/category/online-2-player/">{"online 2-player games"}</Link>{" or the broader "}<Link href="/category/multiplayer/">{"multiplayer collection"}</Link>{" for room-based sessions. Games marked \"both\" work either way."}</p>
        <h2>{"Frequently asked questions"}</h2>
        <div><h3>{"What makes a browser game good for a party?"}</h3><p>{"Short rounds, minimal rules, and something entertaining to watch. Races and duels tend to work best because the winner is obvious. Turn-based games slow the room down unless the group is specifically in the mood for that."}</p></div>
        <div><h3>{"Can 3 or 4 people play these on one computer?"}</h3><p>{"A few of them, yes. Fish Eat Getting Big and Fish Eat Fish 2 document three-player setups on one device. For four or more people, most games work better as a rotation – one player challenges the winner of the last round."}</p></div>
        <div><h3>{"Are party games always competitive?"}</h3><p>{"No. Cooperative party games (Multiplayer Cooking Coop) work well when the group wants to beat a shared challenge instead of each other. Both formats fit under \"party\" depending on what the group is in the mood for."}</p></div>
        <div><h3>{"Do party games need voice chat?"}</h3><p>{"Not usually. Local party games are played in the same room so people can just talk. Online party games can be played over Discord or a phone call if the group wants coordination, but nothing on this list requires it."}</p></div>
        <p>For shared-device picks, browse <Link href="/category/local-2-player/">local two-player games</Link>. Our <Link href="/blog/best-2-player-browser-games/">two-player browser game testing guide</Link> explains the setups.</p>
      </section>}
      {isBoardCard && <section className="prose-copy mt-14">
        <h2>{"Classic 2 player board games in your browser"}</h2>
        <p>{"Standard board games with the standard rules – no reinvention, no gimmicks. "}<Link href="/games/master-checkers-multiplayer/">{"Master Checkers Multiplayer"}</Link>{" and "}<Link href="/games/turkish-draughts/">{"Turkish Draughts"}</Link>{" both use forced captures and back-rank promotion. "}<Link href="/games/backgammonia-online-backgammon-game/">{"Backgammonia"}</Link>{" covers the dice-and-blot rules of backgammon. "}<Link href="/games/chess-multiplayer-online/">{"Chess Multiplayer Online"}</Link>{" runs standard chess with online matchmaking. "}<Link href="/games/reversi-multiplayer/">{"Reversi Multiplayer"}</Link>{" is Othello under a different name. If you already know the tabletop version, you can jump in immediately."}</p>
        <h2>{"Card games for 2, 3 or 4 players"}</h2>
        <p><Link href="/games/whot-the-ultimate-nigerian-card-game/">{"WHOT"}</Link>{" is the hugely popular Nigerian card game – match shape or number, empty your hand first. "}<Link href="/games/dominoes-classic-duel/">{"Dominoes Classic Duel"}</Link>{" and "}<Link href="/games/domino-online-multiplayer/">{"Domino Online Multiplayer"}</Link>{" both run the 28-tile classic. "}<Link href="/games/4-colors-multiplayer/">{"4 Colors Multiplayer"}</Link>{", "}<Link href="/games/duo-with-online-friends-multiplayer-card-game/">{"DUO With Friends"}</Link>{" and "}<Link href="/games/last-card-multiplayer/">{"Last Card Multiplayer"}</Link>{" are all Uno-style card games with slight variations."}</p>
        <h2>{"Simple 3-in-a-row and connect games"}</h2>
        <p>{"Fastest games in the catalog. "}<Link href="/games/tic-tac-toe-pro-multiplayer-challenge/">{"Tic Tac Toe Pro"}</Link>{" runs under a minute per match, which makes it a great rematch loop. "}<Link href="/games/straight-4-multiplayer/">{"Straight 4 Multiplayer"}</Link>{" is Connect Four – drop discs, block diagonals, four in a row wins."}</p>
        <h2>{"Strategy card and battle games"}</h2>
        <p><Link href="/games/castle-wars-legacy/">{"Castle Wars: Legacy"}</Link>{" combines deck-building with resource management – closer to a card RPG than a straight card game. "}<Link href="/games/battle-jitsu/">{"Battle Jitsu"}</Link>{" uses a faster fire/water/ice counter system for quick matches."}</p>
        <h2>{"Backgammon, ludo and dice-based classics"}</h2>
        <p>{"Turn-based games where dice add variance. "}<Link href="/games/backgammonia-online-backgammon-game/">{"Backgammonia"}</Link>{" is standard backgammon. "}<Link href="/games/ludo-game-multiplayer/">{"Ludo Game Multiplayer"}</Link>{" covers the classic Ludo/Parcheesi race. "}<Link href="/games/snake-and-ladders-multiplayer/">{"Snakes and Ladders Multiplayer"}</Link>{" is the children's classic – no strategy, but works for a mixed-age session."}</p>
        <h2>{"Play with a friend, or practice against AI"}</h2>
        <p>{"Most games here support at least one of: online play against a real opponent, pass-and-play on one device, or AI practice. Games labeled \"both\" work either way. For pass-and-play specifically, browse "}<Link href="/category/local-2-player/">{"local 2-player games"}</Link>{". For online duels, "}<Link href="/category/online-2-player/">{"online 2-player games"}</Link>{" has the full list."}</p>
        <h2>{"Frequently asked questions"}</h2>
        <div><h3>{"Can I play these against another person, or only the computer?"}</h3><p>{"Every game here has at least one two-player mode – either online, pass-and-play on one device, or both. AI is available on many titles as a practice option, but \"AI only\" games aren't included in this collection."}</p></div>
        <div><h3>{"Do I need to know the rules first?"}</h3><p>{"Simple games (Tic Tac Toe Pro, Straight 4, Snakes and Ladders) don't need any prep. Chess, checkers, backgammon, WHOT and Castle Wars all have deeper rules – each game page includes controls and objective."}</p></div>
        <div><h3>{"Are these games turn-based?"}</h3><p>{"Most are, yes. Carrom Pro is physics-based (aim and shoot), Battle Jitsu uses faster card choices, but the rest of the collection is standard alternating turns."}</p></div>
        <div><h3>{"Can I play chess or checkers with a specific friend?"}</h3><p>{"Chess Multiplayer Online and Master Checkers Multiplayer both support online play. Whether they use room codes or public matchmaking depends on the specific game – check the game page."}</p></div>
        <p>For a tabletop aiming option, try <Link href="/games/carrom-pro/">Carrom Pro</Link>. Our <Link href="/blog/best-2-player-browser-games/">two-player browser game testing guide</Link> compares controls and modes.</p>
      </section>}
      {isSportsRacing && <section className="prose-copy mt-14">
        <h2>{"Paddle and ball games for 2 players"}</h2>
        <p>{"Fast head-to-head games built around one clear mechanic. "}<Link href="/games/multiplayer-pong/">{"Multiplayer Pong"}</Link>{" is the online version – find a random opponent, best of five, done in two minutes. "}<Link href="/games/table-pong/">{"Table Pong"}</Link>{" covers the local same-keyboard version. "}<Link href="/games/pingpong-dot/">{"Pingpong Dot"}</Link>{" is a lighter arcade-style take. All three finish quickly enough for rematches without a long tutorial."}</p>
        <h2>{"Aiming games – darts, billiards and carrom"}</h2>
        <p>{"The slower half of the sports category. "}<Link href="/games/darts-pro-multiplayer/">{"Darts Pro Multiplayer"}</Link>{" rewards consistency over reflex. "}<Link href="/games/billiard-champion/">{"Billiard Champion"}</Link>{" is standard 8-ball pool – aim, add spin, plan two shots ahead. "}<Link href="/games/carrom-pro/">{"Carrom Pro"}</Link>{" sits between the two: physics-based shots with power and angle decisions, three different rulesets on one board."}</p>
        <h2>{"Arcade soccer and vehicle competition"}</h2>
        <p><Link href="/games/rocketcar-cup/">{"Rocketcar Cup"}</Link>{" combines car movement with arcade soccer – manage acceleration, boosts and contact with the ball rather than following a racing line. Works well as a spectator game because the ball is always the focus."}</p>
        <h2>{"Obstacle races and finish-line games"}</h2>
        <p>{"Racing here doesn't just mean cars. "}<Link href="/games/ninja-parkour-multiplayer/">{"Ninja Parkour Multiplayer"}</Link>{" is a vertical parkour race – jump between lanterns and pagoda rooftops, whoever climbs highest wins. "}<Link href="/games/brainrot-bridge-race-3d/">{"Brainrot Bridge Race 3D"}</Link>{" and "}<Link href="/games/ballon-race-3d/">{"Ballon Race 3D"}</Link>{" are traditional finish-line formats with collection or obstacle mechanics. "}<Link href="/games/aquapark-balls-party/">{"Aquapark Balls Party"}</Link>{" uses a knockout-style water park course."}</p>
        <h2>{"Bowling and precision competition"}</h2>
        <p><Link href="/games/bowling-hero-multiplayer/">{"Bowling Hero Multiplayer"}</Link>{" covers standard 10-pin bowling with local and online modes. "}<Link href="/games/penalty-challenge-multiplayer/">{"Penalty Kick"}</Link>{" is the classic soccer penalty shootout – strikes, saves, done in a couple of minutes."}</p>
        <h2>{"Local or online sports competition?"}</h2>
        <p>{"For same-room competition, use games with \"local\" or \"both\" tags. If you're playing an opponent remotely, filter to online titles or check "}<Link href="/category/online-2-player/">{"online 2-player games"}</Link>{" for the full list. Public arena sports (Rocketcar Cup) also appear in "}<Link href="/category/multiplayer/">{"multiplayer"}</Link>{" if you want larger sessions."}</p>
        <h2>{"Frequently asked questions"}</h2>
        <div><h3>{"Which sports games work with two players sharing one device?"}</h3><p>{"Table Pong, Carrom Pro, Aquapark Balls Party and Penalty Kick all support shared-device play. Multiplayer Pong, Ninja Parkour Multiplayer and Rocketcar Cup are online-only."}</p></div>
        <div><h3>{"Are all racing games car games?"}</h3><p>{"No. Racing here means any game built around crossing a finish line first – parkour, bridge races, balloon races and water-park courses as well as vehicle competition. Filter by game title on each card if you specifically want cars."}</p></div>
        <div><h3>{"Do I need a gamepad?"}</h3><p>{"No. Every game here works on keyboard and mouse. Aiming games (darts, billiards, carrom) mostly use the mouse. Racing and parkour games use keyboard. A gamepad works on some titles but nothing requires it."}</p></div>
        <div><h3>{"Can I practice sports games alone?"}</h3><p>{"Depends on the game. Bowling Hero, Penalty Kick and Darts Pro Multiplayer all include solo modes. Multiplayer Pong is online-only – you need a live opponent."}</p></div>
        <p>For more same-device options, browse <Link href="/category/local-2-player/">local two-player games</Link>. Our <Link href="/blog/best-2-player-browser-games/">two-player browser game testing guide</Link> covers the controls.</p>
      </section>}
      {isIoArena && <section className="prose-copy mt-14">
        <h2>{"What is an IO game?"}</h2>
        <p>{"IO games are lightweight browser games built around quick public matches – shared arenas, simple controls, dozens of players in one session. The name comes from `.io` domains (agar.io, slither.io) that popularized the format. The tag alone doesn't guarantee anything – games only make this collection if the multiplayer or arena behavior is verified. AI-only games with a misleading \"io\" tag don't count."}</p>
        <h2>{"Battle royale and survival IO games"}</h2>
        <p>{"Last-player-standing formats. "}<Link href="/games/survev-io/">{"Survev.io"}</Link>{" is a top-down battle royale – loot buildings for weapons and gear, stay inside a shrinking safe zone, be the last one alive. "}<Link href="/games/snake-war-multiplayer/">{"Snake War Multiplayer"}</Link>{" uses the slither.io formula: grow by eating, trap rivals with your body, don't run into anyone else. "}<Link href="/games/tung-sahur-io/">{"Tung Sahur IO"}</Link>{" turns a large public session into an infection-style chase where the tagged player becomes the tagger."}</p>
        <h2>{"Territory painting and movement arenas"}</h2>
        <p><Link href="/games/color-path-io/">{"Color Path IO"}</Link>{" uses the paper.io mechanic – draw a line, close a shape, claim the space. "}<Link href="/games/speen/">{"Speen"}</Link>{" has one weird mechanic: two connected circles swap pivots to swing through the world, collecting pickups and duelling other players in shared territory. "}<Link href="/games/greedy-snake-multiplayer-duel/">{"Greedy Snake Multiplayer Duel"}</Link>{" is a simpler head-to-head take on the snake formula."}</p>
        <h2>{"Team battles and arena combat"}</h2>
        <p><Link href="/games/guardz-io/">{"Guardz IO"}</Link>{", "}<Link href="/games/growwars-io/">{"GrowWars.io"}</Link>{" and "}<Link href="/games/viking-tomahawk/">{"Viking Tomahawk"}</Link>{" focus on direct combat in public arenas. Weapon and combat intensity varies from cartoon-style contact to genuine arena shooters, so check the game description before choosing."}</p>
        <h2>{"Social deduction and trivia lobbies"}</h2>
        <p>{"Not every IO game is combat. "}<Link href="/games/imposter-duck-online/">{"Imposter Duck: Online"}</Link>{" is a social deduction game with hidden roles – closer to Among Us than to a shooter. "}<Link href="/games/quiz-runner-io/">{"Quiz Runner.io"}</Link>{" combines trivia with a real-time race. "}<Link href="/games/rocketcar-cup/">{"Rocketcar Cup"}</Link>{" turns an arena into arcade soccer."}</p>
        <h2>{"Party formats in IO games"}</h2>
        <p><Link href="/games/gang-fall-party/">{"Gang Fall Party"}</Link>{" runs Fall Guys-style knockout rounds with public opponents. "}<Link href="/games/aquapark-balls-party/">{"Aquapark Balls Party"}</Link>{" uses a water-park course. Both work as party games too and appear in the "}<Link href="/category/party/">{"party collection"}</Link>{"."}</p>
        <h2>{"Frequently asked questions"}</h2>
        <div><h3>{"Are all IO games battle royale?"}</h3><p>{"No. This collection covers territory games, snake survival, social deduction, trivia races, arena combat and team sports. Battle royale is one of several IO formats."}</p></div>
        <div><h3>{"Can I play IO games with a specific friend?"}</h3><p>{"Some games (Imposter Duck, Rocketcar Cup) expose room or friend options. Most public arenas (Survev.io, Snake War) use pure public matchmaking – you can both join the same server but you might not end up in the same match."}</p></div>
        <div><h3>{"Do these games have weapons or violence?"}</h3><p>{"Some do. Survev.io, GrowWars.io and Viking Tomahawk include weapons in a cartoon or top-down style. Territory and racing games (Color Path IO, Speen, Rocketcar Cup) don't. Each game page describes the combat style."}</p></div>
        <div><h3>{"Why is the count smaller than other IO sites?"}</h3><p>{"Because a game only makes the list if the multiplayer mode actually works during review. A lot of games tagged \".io\" or \"arena\" on supplier catalogs turn out to be AI-only or have no active players. Those get filtered out."}</p></div>
        <p>For a planned duel, browse <Link href="/category/online-2-player/">online two-player games</Link>; for more team and co-op options, see <Link href="/category/multiplayer/">multiplayer games</Link>.</p>
      </section>}
    </div>
  );
}
